services:
  _defaults:
    public: true

  prestashop.module.featurenavigator.form.type.configuration:
    class: 'PrestaShop\Module\FeatureNavigator\Form\FeatureNavigatorConfigurationFormType'
    parent: 'form.type.translatable.aware'
    public: true
    arguments:
      - '@prestashop.adapter.form.choice_provider.features_choice_provider'
    tags:
      - { name: form.type }

  prestashop.module.featurenavigator.form.data_configuration:
    class: 'PrestaShop\Module\FeatureNavigator\Form\FeatureNavigatorDataConfiguration'
    arguments: ['@prestashop.adapter.legacy.configuration']

  prestashop.module.featurenavigator.form.form_data_provider:
    class: 'PrestaShop\Module\FeatureNavigator\Form\FeatureNavigatorFormDataProvider'
    arguments:
      - '@prestashop.module.featurenavigator.form.data_configuration'

  prestashop.module.featurenavigator.form.form_data_handler:
    class: 'PrestaShop\PrestaShop\Core\Form\Handler'
    arguments:
      - '@form.factory'
      - '@prestashop.core.hook.dispatcher'
      - '@prestashop.module.featurenavigator.form.form_data_provider'
      - 'PrestaShop\Module\FeatureNavigator\Form\FeatureNavigatorConfigurationFormType'
      - 'FeatureNavigatorConfiguration'